/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function ping(): string
/**
 * Lattice commitment round-trip check: extract(commit(m)) == m for a random
 * full-range message. Returns true on success.
 */
export declare function latticeEncRoundtripTest(d: number, k: number, sqrtQ: string, seed: number): boolean
/**
 * Generate the global public commitment matrix A (M×K×d, NTT domain, row-major
 * [m][k][i]) derived deterministically from `seed`. Rows 0..κ_sis are the SIS
 * block; the last two rows are the structured B, B' rows.
 */
export declare function latticeKeygen(d: number, k: number, seed: number): Array<string>
/**
 * Commit to an NTT-domain message vector under the global key `seed`, using
 * fresh ternary randomness from `r_seed`. Returns c flattened row-major (M×d).
 */
export declare function latticeCommitNtt(d: number, k: number, sqrtQ: string, seed: number, valsNtt: Array<string>, rSeed: number): Array<string>
/**
 * Decrypt an NTT-domain commitment (flattened row-major M×d) under key `seed`.
 * Returns the recovered NTT-domain message vector (length d).
 */
export declare function latticeExtractNtt(d: number, k: number, sqrtQ: string, seed: number, cFlat: Array<string>): Array<string>
/** Shared SIS block A_sis (κ_sis×K×d, NTT domain, row-major) from a global seed. */
export declare function latticeKeygenSis(d: number, k: number, seedSis: number): Array<string>
/**
 * Full per-recipient matrix A_R = [A_sis ; B_R ; B'_R] (M×K×d, row-major).
 * A_sis from `seed_sis` (shared), B rows from `seed_r` (recipient).
 */
export declare function latticeKeygenRecipient(d: number, k: number, seedSis: number, seedR: number): Array<string>
/** Commit under a recipient key (A_sis from `seed_sis`, B from `seed_r`). */
export declare function latticeCommitNttR(d: number, k: number, sqrtQ: string, seedSis: number, seedR: number, valsNtt: Array<string>, rSeed: number): Array<string>
/** Decrypt under a recipient key (A_sis from `seed_sis`, secret from `seed_r`). */
export declare function latticeExtractNttR(d: number, k: number, sqrtQ: string, seedSis: number, seedR: number, cFlat: Array<string>): Array<string>
export declare function fieldMulTest(a: string, b: string): string
export declare function transcriptInitHex(): string
export declare function leafHashTest(): string
export declare function rescueHashTest(coeffsStr: Array<string>): Array<string>
export declare function nttRoundtripTest(size: number): boolean
/**
 * Full prover entry point called from TypeScript.
 * Accepts all inputs as string arrays (BigInt doesn't cross NAPI natively),
 * builds A-oracle setup in Rust, runs the prover, returns JSON proof.
 */
export declare function proveRangeHash(aMatFlat: Array<string>, mCount: number, kCount: number, d: number, bCoeffsFlat: Array<string>, mNtt: Array<string>, mOrigNtt: Array<string>, mSenderNtt: Array<string>, sqrtQ: string, cNttsFlat: Array<string>, tokenM: Array<string>, tokenS: Array<string>, tokenO: Array<string>, grindingBits?: number | undefined | null): string
